name: CI

on:
  push:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: shanakaprageeth/ubuntu24-dpdk:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get -qq update
        apt-get -qq install -y libssl-dev ninja-build
        git config --global --add safe.directory `pwd`
        git submodule update --init --recursive
    - name: Compile igb_uio
      run: |
        make -C /lib/modules/6.8.0-64-generic/build M=`pwd`/dpdk-kmods/linux/igb_uio
    - name: Compile dpdk
      run: |
        cd dpdk
        meson setup build
        ninja -C build install
    - name: Compile spdk
      run: |
        cd spdk
        ./scripts/pkgdep.sh
        ./configure --disable-tests --disable-unit-tests --disable-examples --disable-apps --with-dpdk=/usr/local/lib/x86_64-linux-gnu/
        make
    - name: Compile f-stack
      run: |
        cd lib/
        make
    - name: Archive production artifacts
      if: github.ref_name == 'master' || github.ref_name == 'dev'
      uses: actions/upload-artifact@v4
      with:
        name: build_output
        path: |
          dpdk/build
          lib
